language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4  
  - hhvm
  
script:
  - echo 'Iriven PHP Form Generator Library'
  
before_install:
  - travis_retry composer self-update

install:
- composer install
